//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondsCardsControlFrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class CortesiasConsumida
    {
        public long Id { get; set; }
        public long CourtesyId { get; set; }
        public int CourtesyTypeId { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
