//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondsCardsControlFrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courtesy
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Invitation { get; set; }
        public string NombreCliente { get; set; }
        public string Vuelo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int SinConsumir { get; set; }
        public string CourtesyType { get; set; }
    }
}
