//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondsCardsControlFrm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiamondsClient
    {
        public long Id { get; set; }
        public string Supervisor { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Vuelo { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Nombre { get; set; }
        public string Edad { get; set; }
        public string DocumentoHabilitante { get; set; }
        public string NoDelDocTarjetaCredito { get; set; }
        public string NoDelDocHabilVoucher { get; set; }
        public string NoInvitacionLineaAerea { get; set; }
        public string DescripcionTC { get; set; }
        public string Observaciones { get; set; }
        public string Coordinador { get; set; }
        public string Descripcion { get; set; }
        public string NumeroSala { get; set; }
        public string Banco { get; set; }
        public string Aerolinea { get; set; }
        public string Aprobacion { get; set; }
        public string DocIdentidad { get; set; }
        public string Ciudad { get; set; }
        public Nullable<bool> CourtesyAvailable { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
