//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiamondsCardsControlFrm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiamondsEntities : DbContext
    {
        public DiamondsEntities()
            : base("name=DiamondsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Banco> Bancoes { get; set; }
        public virtual DbSet<Patrocinador> Patrocinadors { get; set; }
        public virtual DbSet<TipoTarjeta> TipoTarjetas { get; set; }
        public virtual DbSet<SalaVIP> SalaVIPs { get; set; }
        public virtual DbSet<AereoLinea> AereoLineas { get; set; }
        public virtual DbSet<DescriptionCard> DescriptionCards { get; set; }
        public virtual DbSet<DiamondsClient> DiamondsClients { get; set; }
        public virtual DbSet<CourtesyType> CourtesyTypes { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<CortesiasConsumida> CortesiasConsumidas { get; set; }
        public virtual DbSet<Courtesy> Courtesies { get; set; }
        public virtual DbSet<CreditCard> CreditCards { get; set; }
    }
}
